import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Random;
import net.minecraft.SharedConstants;
import net.minecraft.core.BlockPos;
import net.minecraft.server.Bootstrap;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.ClipContext;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.material.FluidState;
import net.minecraft.world.phys.BlockHitResult;
import net.minecraft.world.phys.HitResult;
import net.minecraft.world.phys.Vec3;
import net.minecraft.world.phys.shapes.CollisionContext;

/**
 * Random rays through a small patterned world, with what BlockGetter.clip
 * (outline shapes, no fluids) returns for each: test vectors for the Rust
 * ray cast.
 */
public class ClipVectors {
    public static void main(String[] args) throws Exception {
        SharedConstants.tryDetectVersion();
        Bootstrap.bootStrap();
        BlockState air = Blocks.AIR.defaultBlockState();
        BlockState[] palette = {
            Blocks.STONE.defaultBlockState(), air, air, Blocks.OAK_SLAB.defaultBlockState(), air,
            Blocks.OAK_STAIRS.defaultBlockState(), air, air, Blocks.OAK_FENCE.defaultBlockState(), air,
            Blocks.LADDER.defaultBlockState(), air, Blocks.COBBLESTONE_WALL.defaultBlockState(), air, air,
            Blocks.LANTERN.defaultBlockState(), air, Blocks.OAK_TRAPDOOR.defaultBlockState(), air, air,
            Blocks.CAULDRON.defaultBlockState(), air, Blocks.SNOW.defaultBlockState(), air, Blocks.TORCH.defaultBlockState(),
        };
        BlockGetter level = new BlockGetter() {
            public BlockEntity getBlockEntity(BlockPos pos) { return null; }
            public BlockState getBlockState(BlockPos pos) {
                int x = pos.getX(), y = pos.getY(), z = pos.getZ();
                if (x < 0 || y < 0 || z < 0 || x >= 6 || y >= 6 || z >= 6) return air;
                return palette[(x * 7 + y * 13 + z * 31) % palette.length];
            }
            public FluidState getFluidState(BlockPos pos) { return getBlockState(pos).getFluidState(); }
            public int getMinY() { return -64; }
            public int getHeight() { return 384; }
        };
        Random random = new Random(26_3);
        try (Writer w = Files.newBufferedWriter(Path.of(args[0]), StandardCharsets.UTF_8)) {
            w.write("# Generated by tools/gen_clip_vectors.py. Line 2: palette state IDs; block (x,y,z) in 0..6 is palette[(7x+13y+31z) % len].\n");
            StringBuilder ids = new StringBuilder();
            for (BlockState s : palette) ids.append(Block.getId(s)).append(' ');
            w.write(ids.toString().trim() + "\n");
            w.write("# from xyz, to xyz (double bits), miss, block xyz, direction ordinal, inside, location xyz (double bits)\n");
            for (int i = 0; i < 4000; i++) {
                Vec3 from = new Vec3(random.nextDouble() * 8 - 1, random.nextDouble() * 8 - 1, random.nextDouble() * 8 - 1);
                Vec3 to;
                if (i % 10 == 0) {
                    // Axis-aligned rays hit the sign == 0 branches.
                    to = from.add(i % 20 == 0 ? 5 : 0, i % 30 == 0 ? -4 : 0, i % 20 == 0 ? 0 : -6);
                } else {
                    double len = 0.5 + random.nextDouble() * 6;
                    Vec3 dir = new Vec3(random.nextGaussian(), random.nextGaussian(), random.nextGaussian()).normalize();
                    to = from.add(dir.scale(len));
                }
                BlockHitResult hit = level.clip(new ClipContext(from, to, ClipContext.Block.OUTLINE, ClipContext.Fluid.NONE, CollisionContext.empty()));
                Vec3 at = hit.getLocation();
                w.write(bits(from.x) + " " + bits(from.y) + " " + bits(from.z) + " " + bits(to.x) + " " + bits(to.y) + " " + bits(to.z) + " "
                    + (hit.getType() == HitResult.Type.MISS ? 1 : 0) + " "
                    + hit.getBlockPos().getX() + " " + hit.getBlockPos().getY() + " " + hit.getBlockPos().getZ() + " "
                    + hit.getDirection().ordinal() + " " + (hit.isInside() ? 1 : 0) + " "
                    + bits(at.x) + " " + bits(at.y) + " " + bits(at.z) + "\n");
            }
        }
    }

    private static String bits(double d) {
        return Long.toHexString(Double.doubleToRawLongBits(d));
    }
}
