[package]
name = "rapidbot-protocol"
description = "Minecraft protocol: framing, compression, encryption and packets"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rapidbot-buf.workspace = true
aes.workspace = true
cfb8.workspace = true
flate2.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true
rapidbot-nbt.workspace = true
