#!/usr/bin/env python3
"""Generate crates/protocol/src/ids.rs from vanilla's data generator reports.

Run tools/fetch_vanilla.py first.

    python tools/gen_packet_ids.py 26.3
"""

import json
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STATES = ["handshake", "status", "login", "configuration", "play"]


def main() -> None:
    version = sys.argv[1] if len(sys.argv) > 1 else "26.3"
    base = ROOT / "vanilla" / version
    packets = json.loads((base / "generated" / "reports" / "packets.json").read_text())
    with zipfile.ZipFile(base / "versions" / version / f"server-{version}.jar") as z:
        info = json.loads(z.read("version.json"))

    out = [
        f"//! Packet IDs for Minecraft {info['name']}.",
        "//!",
        "//! Generated by tools/gen_packet_ids.py from vanilla's packets.json. Do not edit.",
        "",
        f"pub const PROTOCOL_VERSION: i32 = {info['protocol_version']};",
        f'pub const VERSION_NAME: &str = "{info["name"]}";',
        f'/// `WorldVersion.id()`.',
        f'pub const VERSION_ID: &str = "{info["id"]}";',
        "/// `PackFormat.toString()` of the client resource pack format.",
        f'pub const RESOURCE_PACK_FORMAT: &str = "{info["pack_version"]["resource_major"]}.{info["pack_version"]["resource_minor"]}";',
        "",
    ]
    for state in STATES:
        out.append(f"pub mod {state} {{")
        for direction in ("clientbound", "serverbound"):
            ids = packets.get(state, {}).get(direction)
            if not ids:
                continue
            ordered = sorted(ids.items(), key=lambda kv: kv[1]["protocol_id"])
            out.append(f"    pub mod {direction} {{")
            for name, v in ordered:
                const = name.removeprefix("minecraft:").replace("/", "_").upper()
                out.append(f"        pub const {const}: i32 = {v['protocol_id']};")
            names = ", ".join(f'"{n.removeprefix("minecraft:")}"' for n, _ in ordered)
            out.append("")
            out.append("        /// Packet names indexed by ID, for logging.")
            out.append(f"        pub const NAMES: &[&str] = &[{names}];")
            out.append("    }")
        out.append("}")
        out.append("")

    dest = ROOT / "crates" / "protocol" / "src" / "ids.rs"
    dest.write_text("\n".join(out))
    print(f"wrote {dest} (protocol {info['protocol_version']})")


if __name__ == "__main__":
    main()
